mail:
    host: localhost
    password: ''
    port: 1025
    username: admin@example.com
mobilele:
    admin:
        defaultpass: ${DEFAULT_PASS:test}
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/futsal?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    sql:
        init:
            mode: embedded
